#! /bin/bash
#: Title		: insert_string
#: Description	: Insert one string into another at a specified location
#: Options		: None

_insert_string()
{ #@ USAGE: _insert_string STRING INSERTION [POSITION]
  #@ RESULT: in _INSERT_STRING
  
  local string=$1     ## container string
  local i_string=$2   ## string to be inserted
  local i_pos=${3:-2} ## insert location
  local left right    ## before and after strings

  left=${string:0:$(($i_pos - 1))}    ## string to left of insert
  right=${string:$(($i_pos - 1))}     ## string to right of insert
  _INSERT_STRING=$left$i_string$right ## build new string
}

insert_string()
{
  _insert_string "$@" && printf "%s\n" "$_INSERT_STRING"
}
