#! /bin/bash
#: Title		    : alert
#: Description	: Print a warning message with a border and a beep
#: Options		  : None

## Original name was alert, but there is already a command in Ubuntu with
## that name. Refactored to message_w_border to avoid problems.

message_w_border()
{ #@ USAGE: message_w_border MESSAGE BORDER
  #@ RESULT: printed
  
  source repeat

  _repeat "${2:-#}" $((${#1} + 8))
  printf "\a%s\n" "$_REPEAT" ## \a == BEL
  printf "%2.2s  %s  %2.2s\n" "$_REPEAT" "$1" "$_REPEAT"
  printf "%s\n" "$_REPEAT"
}
