#! /bin/bash
#: Title		: repeat
#: Description	: Repeat a string n times
#: Options		: None

function _repeat()
{
  #@ USAGE: _repeat char number
  #@ RESULT: in _REPEAT

  [ $# -ne 2 ] && exit 1

  _REPEAT=$1
  while ((${#_REPEAT} < $2)); do     ## Loop until string exceeds desired length
    _REPEAT=$_REPEAT$_REPEAT$_REPEAT ## 3 seems to be the optimum number
  done

  _REPEAT=${_REPEAT:0:$2} ## Trim to desired length
}

repeat()
{
  _repeat "$@"
  printf "%s\n" "$_REPEAT"
}
