#! /bin/bash
#: Title		: Not Greater Than Ten
#: Date			: 2021/09/23
#: Options		: None

printf "Enter a number not grater than 10: "
read number
if (( number > 10 ))
then
    printf "%d is too big\n" "$number" >&2
    exit 1
else
    printf "You entered %d\n" "$number"
fi
