#! /bin/bash
#: Title		: _max3-func
#: Description	: sort three integers
#: Options		: None

_max3() #@ USAGE: _max3 INTEGER INTEGER INTEGER
#@ Sort 3 integers and store in $_MAX3, $_MID3, and $_MIN3
{
    [ $# -ne 3 ] && return 5
    [ $1 -gt $2 ] && { set -- $2 $1 $3; }
    [ $2 -gt $3 ] && { set -- $1 $3 $2; }
    [ $1 -gt $2 ] && { set -- $2 $1 $3; }
    _MAX3=$3
    _MID3=$2
    _MIN3=$1
}

max3() #@ USAGE: max3 N1 N2 N3 [VARNAME]
#@ Sort 3 integers and store in an array
{
    declare -n _max3=${4:-_MAX3}
    (( $# < 3 )) && return 4
    (( $1 > $2 )) && set -- "$2" "$1" "$3"
    (( $2 > $3 )) && set -- "$1" "$3" "$2"
    (( $1 > $2 )) && set -- "$2" "$1" "$3"
    _max3=( "$3" "$2" "$1" )
}