#! /bin/bash
#: Title		: valint
#: Description	: Check for valid integer
#: Options		: None

valint() #@ USAGE: valint INTEGER
    case ${1#-} in ## Leading hyphen removed to accept negative numbers
        *[!0-9]*) false ;; ## the string contains a non-digit character
        *) true ;; ## the whole number, and nothing but the number
    esac

    ## The program is a single compound command, so braces are not necessary
    
